title: "Your Name"
description: "Experimental condensed matter physicist — crystal growth, magnetism & quantum materials"
theme: jekyll-theme-minimal
# Optional: set a logo image file in the repo (e.g., /assets/profile.jpg)
# logo: /assets/profile.jpg
# Optional: add your Google Analytics ID
# google_analytics: G-XXXXXXXXXX
