# ==============================
#   Personal Website Config
# ==============================

title: ""
name: "Anzar Ali"
description: "Experimental condensed matter physicist — crystal growth, magnetism & quantum materials"
url: "https://alianzar03.github.io"   # <-- change 'alianzar03' if your GitHub username is different
baseurl: ""   # leave blank for username.github.io

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Minimal Mistakes settings
minimal_mistakes_skin: "default"  # options: default, dark, contrast, mint, neon, etc.

# Author profile (sidebar info)
author:
  name: "Anzar Ali"
  avatar: "/assets/profile.jpg"   # put your photo here
  bio: "Experimental Condensed Matter Physicist  
  Crystal growth • Magnetism • Quantum materials"
  location: "Stuttgart, Germany"
  links:
    - label: "Research"
      icon: "fas fa-flask"
      url: "/research/"
    - label: "Publications"
      icon: "fas fa-book"
      url: "/publications/"
    - label: "CV"
      icon: "fas fa-file-pdf"
      url: "/cv/CV_Anzar_Ali.pdf"
    - label: "Contact"
      icon: "fas fa-envelope"
      url: "/contact/"

# Site navigation
navigation:
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "CV"
    url: /cv/CV_Anzar_Ali.pdf
  - title: "Contact"
    url: /contact/

# Plugins (all supported on GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

# Pagination (for blog if you add posts)
paginate: 5
paginate_path: /page:num/

# Defaults for pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
